# Generated by Django 5.1.2 on 2024-10-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.CharField(db_column='id')),
                ('NIPCC', models.IntegerField(primary_key=True, serialize=False)),
                ('DENOMINACAO', models.CharField(max_length=255)),
                ('ATV_ID', models.IntegerField()),
                ('OBJ_ID', models.IntegerField()),
                ('SEDE_CEP', models.IntegerField()),
                ('SEDE_ENDERECO', models.CharField(max_length=255)),
                ('CID_ID', models.IntegerField()),
                ('DST_ID', models.IntegerField()),
                ('CEP_INTERVENCAO', models.IntegerField()),
                ('END_INTERVENCAO', models.CharField(max_length=255)),
                ('EMAIL', models.CharField(max_length=255)),
                ('SENHA', models.CharField(max_length=255)),
                ('CONFIRMACAO_SENHA', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estabelecimento',
                'managed': False,
            },
        ),
    ]
