# Generated by Django 5.1.2 on 2024-10-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('atv_id', models.IntegerField(primary_key=True, serialize=False)),
                ('atv_descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'atividade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('cid_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cid_descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('dst_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dst_descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'distrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('eqp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('eqp_descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'equipamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('obj_id', models.IntegerField(primary_key=True, serialize=False)),
                ('obj_descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'objeto',
                'managed': False,
            },
        ),
    ]
